### PR TITLE
Added rspec test for connect/bound

### LINKED ISSUE #9: Log output should say "bound" if in server mode
https://github.com/logstash-plugins/logstash-output-zeromq/blob/master/lib/logstash/util/zeromq.rb#L21

### PR DESCRIPTION
**Pull request by breml**
Based on contributing-patch.asciidoc

Fixes: #9 

If this pull request gets merged, https://github.com/elastic/logstash/blame/master/docs/static/contributing-patch.asciidoc#L224 should be updated to reference a commit-hash prior to this bugfix.

### CODE REVIEW

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by nukemberg** [comment]
Not relevant anymore - logstash-mixin-zeromq

**Comment by breml** [comment]
@avishai-ish-shalom The code in logstash-mixin-zeromq is still wrong and does not include the additional tests. I suggest to keep this one open, util logstash-mixin-zeromq is correctly updated.

**Comment by nukemberg** [comment]
yeh, did that :)

**Pull request closed without merging**
